server:
  port: 80

eureka:
  client:
    # 是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须是true才能配合ribbon使用负载均衡
    fetch-registry: true
    # 表示是否将自己注册进eurekaServer
    register-with-eureka: true
    service-url:
      #注册到7001Server端和7002Server端
      defaultZone: http://121.40.237.86:7001/eureka/, http://121.40.237.86:7002/eureka/
ribbon:
  # 指的是建立连接所用的时间，客户端到服务端连接时间，适用于网络正常的情况下
  ReadTimeout: 5000
  # 从服务器读取到可用资源的时间
  ConnectTimeout: 500
logging:
  level:
    edu.ahau.springcloud.openfeign.service.PaymentFeignService: debug
spring:
  application:
    name: cloud-consumer-openfeign-order