server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002
  client:
    # 这个是服务端，不需要注册自己
    register-with-eureka: false
    # false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    # 设置与Eureka Server交互的地址 查询服务和注册服务 都需要依赖这个地址
    service-url:
      defaultZone: http://localhost:7001/eureka/