server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启以微服务名称作为请求
      routes:
        - id: payment8001a
#          uri: http://127.0.0.1:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**
            - After=2021-11-23T23:02:20.741+08:00[Asia/Shanghai]
#            - Cookie=username, zzxx
#            - Header=X-Request-Id, \d+
#            - Host=**.somehost.org,**.anotherhost.org
#            - Method=GET
#            - Query=green
#            - RemoteAddr=127.0.0.1/24
#            - Weight=group1, 8
        - id: payment8001b
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/port
            - Weight=group1, 2



eureka:
  client:
    # 是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须是true才能配合ribbon使用负载均衡
    fetch-registry: true
    # 表示是否将自己注册进eurekaServer
    register-with-eureka: true
    service-url:
      #注册到7001Server端和7002Server端
      defaultZone: http://121.40.237.86:7001/eureka/, http://121.40.237.86:7002/eureka/
  instance:
    instance-id: gateway9527
    prefer-ip-address: true